### ISSUE TITLE
scrolling issue on browsing entry forms

### ISSUE THREAD

**Issue by haraQQiri** [3dem/emhub#125]
reposting issue here, after loading images in the project screening entries forms that allow image uploads, after closing the image there is an issue with scrolling that gets locked and I have to reload the page in order to continue scrolling to other entries. the scroll wheel moves the page in the background instead of the widget window with the images on the foreground 

<img width="1582" height="837" alt="Image" src="https://github.com/user-attachments/assets/d088fb26-26c5-4b37-b562-0011ae726e4c" />

**Comment by delarosatrevin** [comment]
Hi @haraQQiri , thanks for reporting this. I fixed in devel. It was due to an error when trying to display files that haven't been uploaded. Now it will show you an error saying that. Files need to be uploaded before them can be display. Please let me know after you pull from devel and check if fixed for you to close the issue.

**Comment by haraQQiri** [comment]
i updated the devel, unfortunately it seems that the issue is still there, the files were uploaded, i can see the image, and then it's when i close it the scrolling stops. no error message pops up, i can continue to load images from the buttons i see on screen but if more images were uploaded into the entry form i can't scroll up or down on that widget, the scrolling goes back to the page behind it for the project timeline if that makes sense

**Comment by delarosatrevin** [comment]
Got it, I will try to reproduce and further investigate. For me was happing when trying to visualize before uploading

**Comment by delarosatrevin** [comment]
I reproduced and made a small styling change that have solved, at least in my test. Can you pull again from devel and test? Thanks a lot for the feedback.

**Comment by haraQQiri** [comment]
amazing, looks good now! thanks so much!!

**Comment by delarosatrevin** [comment]
Great! Thanks for your help in making EMhub better for everyone.
